moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.5
project:
  name: SageInvest
  mode: personal
  description: ''
  created_at: '2026-02-08 18:54:22'
  template_version: 1.14.5
  optimized: false
